version: '3'

services:
  featureform:
    image: featureformcom/featureform:latest
    ports:
      - "7878:7878"
    environment:
      - FEATUREFORM_HOST=0.0.0.0
      - FEATUREFORM_PORT=7878
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432" 